name: python-package conda in Windows - python 3.8

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file environment_py38.yml
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Lint with flake8
      run: |
        # Activate the base environment
        C:\Miniconda\condabin\conda.bat activate pycgm38
        C:\Miniconda\condabin\conda.bat install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    # Activate the base environment
    #    C:\Miniconda\condabin\conda.bat activate base
    #    C:\Miniconda\condabin\conda.bat install pytest
    #    pytest
